set_property -dict {PACKAGE_PIN V7  IOSTANDARD LVCMOS33} [get_ports I_SNS_ADC_CS_FPGA]
set_property -dict {PACKAGE_PIN U10 IOSTANDARD LVCMOS33} [get_ports I_SNS_ADC_SDI_FPGA]
set_property -dict {PACKAGE_PIN T9  IOSTANDARD LVCMOS33} [get_ports I_SNS_ADC_SCLK_FPGA]
set_property -dict {PACKAGE_PIN Y7  IOSTANDARD LVCMOS33} [get_ports I_SNS_ADC_SDO_FPGA]
set_property -dict {PACKAGE_PIN Y8  IOSTANDARD LVCMOS33} [get_ports ZCR_SNS_ADC_SCLK_FPGA]
set_property -dict {PACKAGE_PIN Y9  IOSTANDARD LVCMOS33} [get_ports ZCR_SNS_ADC_CS_FPGA]
set_property -dict {PACKAGE_PIN W8  IOSTANDARD LVCMOS33} [get_ports ZCR_SNS_ADC_SDO_FPGA]
set_property -dict {PACKAGE_PIN V8  IOSTANDARD LVCMOS33} [get_ports ZCR_SNS_ADC_SDI_FPGA]
set_property -dict {PACKAGE_PIN V5  IOSTANDARD LVCMOS33} [get_ports POWERON_FPGA]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports FAN_PG1_FPGA]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports FAN_HALL1_FPGA]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports FAN_EN1_FPGA]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports FAN_CTRL1_FPGA]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports P_IN_STATUS_FPGA]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports POD_STATUS_FPGA]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports ECTCU_INH_FPGA]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports P_OUT_STATUS_FPGA]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports CCTCU_INH_FPGA]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports SHUTDOWN_OUT_FPGA]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports RESET_OUT_FPGA]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports RTC2FPGA]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports SPARE_OUT_FPGA]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports ESHUTDOWN_OUT_FPGA]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports HV_ADC_SDI_FPGA]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports HV_ADC_SCLK_FPGA]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports HV_ADC_CS_FPGA]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports HV_ADC_SDO_FPGA]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports RELAY_1PH_FPGA]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports RELAY_3PH_FPGA]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports FAN_PG3_FPGA]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS33} [get_ports FAN_HALL3_FPGA]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports FAN_EN3_FPGA]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports FAN_CTRL3_FPGA]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports FAN_PG2_FPGA]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports FAN_HALL2_FPGA]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports FAN_EN2_FPGA]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports FAN_CTRL2_FPGA]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports RS485_RXD_1]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_DE_7]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_TXD_7]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_TXD_8]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports RS485_RXD_8]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports RS485_RXD_9]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_DE_8]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_DE_9]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_TXD_9]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports EN_PFC_FB]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports PG_BUCK_FB]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports EN_PSU_1_FB]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports PG_PSU_1_FB]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports EN_PSU_2_FB]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports PG_PSU_2_FB]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports EN_PSU_5_FB]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports PG_PSU_5_FB]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_DE_1]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_TXD_1]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports EN_PSU_6_FB]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports PG_PSU_6_FB]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports EN_PSU_7_FB]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports PG_PSU_7_FB]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports EN_PSU_8_FB]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports PG_PSU_8_FB]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports EN_PSU_9_FB]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports PG_PSU_9_FB]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports EN_PSU_10_FB]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports PG_PSU_10_FB]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_TXD_2]
set_property -dict {PACKAGE_PIN T12 IOSTANDARD LVCMOS33} [get_ports RS485_RXD_2]
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS33} [get_ports RS485_RXD_3]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_DE_2]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_DE_3]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_TXD_3]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_TXD_4]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports RS485_RXD_4]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports RS485_RXD_5]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_DE_4]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_DE_5]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_TXD_5]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_TXD_6]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports RS485_RXD_6]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports RS485_RXD_7]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports RS485_DE_6]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports UART_RXD_PL]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33 DRIVE 4} [get_ports UART_TXD_PL]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports lamp_status_fpga]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports PH_A_ON_fpga]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports PH_B_ON_fpga]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports PH_C_ON_fpga]


